### ISSUE TITLE
vue: sortOptions property of ReactiveList is not working

### ISSUE THREAD

**Issue by divyanshu-rawat** [appbaseio/reactivesearch#621]
**Issue Type: BUG**
 
**Platform:**
Web (Vue.JS)

**Description:**
`sortOptions` property of `ReactiveList` is not working.
UI is working fine but not the functionality, please find attached gif to get insights on the same.

**Screenshots:**
![bugtwo](https://user-images.githubusercontent.com/13464678/48614886-60f7b900-e9b5-11e8-9b41-6542f958ea28.gif)

**Minimal reproduction of the problem with instructions:**
SandBox where I am encountering this error.
https://codesandbox.io/s/54l2m5rqxl

**Reactivesearch version:**
version 1.0.0-alpha.4

**Browser:** 
I tested it on Browser - Google Chrome Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by bietkul** [comment]
Fixed in `1.0.0-beta`

**Comment by divyanshu-rawat** [comment]
@bietkul this issue is still there, kindly have a look,
I have updated the `sandbox` with the recent version.
